include "reference.conf"

appName="attachment-processor"

metastore {
    refresh_policy = "false"
}

pekko.actor.default-dispatcher {
# Dispatcher is the name of the event-based dispatcher
  type = Dispatcher
  # What kind of ExecutionService to use
  executor = "fork-join-executor"
  # Configuration for the fork join pool
  fork-join-executor {
    # Min number of threads to cap factor-based parallelism number to
    parallelism-min = 2
    # Parallelism (threads) ... ceil(available processors * factor)
    parallelism-factor = 2.0
    # Max number of threads to cap factor-based parallelism number to
    parallelism-max = 10

    # Requirements:
    # 1. JDK 21+
    # 2. add options to the JVM:
    #   - `--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED`
    #   - `--add-opens=java.base/java.lang=ALL-UNNAMED`
    # Virtualize this dispatcher as a virtual-thread-executor
    virtualize = off
  }
  # Throughput defines the maximum number of messages to be
  # processed per actor before the thread jumps to the next actor.
  # Set to 1 for as fair as possible.
  throughput = 100
}

pekko {
  loglevel = "INFO"
  loglevel = ${?LOG_LEVEL}
  loggers = ["org.apache.pekko.event.slf4j.Slf4jLogger"]
  logging-filter = "org.apache.pekko.event.slf4j.Slf4jLoggingFilter"
  logger-startup-timeout = 60s

    connectors.s3 {
      access-style=path
      endpoint-url = "http://localhost:4566"

      aws.credentials {
        provider = static
        access-key-id = ${?AWS_ACCESS_KEY_ID}
        secret-access-key = ${?AWS_SECRET_ACCESS_KEY}
      }
    }
  http {
    server {
      idle-timeout = 1s
      remote-address-header = on
    }
    client {
      idle-timeout = 1s
    }
    host-connection-pool {
      max-connections = 32
      max-open-requests = 64
    }
  }
}

attachment-processor {
  system-params {
    maxBufferSize = 100
    maxBatchSize = 10
    closeOnEmptyReceive = false
    waitTimeSeconds = 20
    messagesPerSecond = 10
    signServiceBufferSize = 10
    esServiceBufferSize = 20
  }

 signatures {
    service-url = "http://localhost:8999"
    signing-profile = "cades-t"
  }

  glacier {
    glacier-url = "http://localhost:8999/glacier"
    glacier-sns = "local"
  }

  elasticsearch {
    elasticsearch-url = "http://nonrep.eu-west-2.es.localhost.localstack.cloud:4566"
  }
}

my-sqs-dispatcher {
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = 16
  }
  throughput = 1
}

my-s3-dispatcher {
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = 16
  }
  throughput = 1
}

my-signing-dispatcher {
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = 16
  }
  throughput = 1
}

my-glacier-dispatcher {
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = 16
  }
  throughput = 1
}

my-metastore-dispatcher {
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = 16
  }
  throughput = 1
}