include "application.conf"

pekko {
  connectors {
    s3 {
      access-style=path
      endpoint-url = "http://127.0.0.1:8010/s3"
      endpoint-url = ${?AWS_ENDPOINT_URL_S3}
    }
  }
}


attachment-processor {
  signatures {
    service-url = "http://127.0.0.1:8010"
    signing-profile = "cades-t"
  }

  glacier {
    glacier-url = "http://localhost:8010/glacier"
    glacier-sns = "local"
  }

  elasticsearch {
    elasticsearch-url = "http://nonrep.eu-west-2.es.localhost.localstack.cloud:4566"
  }
}
