include "application"

pekko {
  connectors {
    s3 {
      endpoint-url = "http://127.0.0.1:8010/s3"
      endpoint-url = ${?AWS_ENDPOINT_URL_S3}

      aws {
        credentials {
          provider = static
          access-key-id = "access-key"
          secret-access-key = "secret-key"
        }
      }
    }
  }
}

attachment-processor {
  sqs {
    sqs-url = "http://sqs.eu-west-2.localhost.localstack.cloud:4566/000000000000/local-nonrep-attachment-queue"
  }

  glacier {
    glacier-url = "http://localhost:8010/glacier"
    glacier-sns = "local"
  }
}